/*
 * Fiktiver Akteursbestand — v0-Arbeitsstand.
 *
 * 36 erfundene Organisationen, schemakonform nach fields.js.
 * Grundlage fuer die Netzdarstellung (schema.html) und die Kreuztabelle
 * (simulation.html). Kein Bezug zu realen Organisationen: Namen sind aus
 * festen Bausteinen zusammengesetzt, Kennzahlen deterministisch erzeugt.
 *
 * Die Eintraege tragen bewusst keine Wikidata-Kennung und keine Adressen —
 * eine QID verweist stets auf eine reale Organisation.
 */

(function (global) {
  'use strict';

  var AKTEURE = [
    {"id":"a01","name":"Denkraum Elbe e. V.","legalForm":"registeredAssociation","status":"active","fieldsOfAction":["languageAndLiteracy"],"primaryFieldOfAction":"languageAndLiteracy","educationStages":["primary"],"targetGroups":[{"role":"multipliers","label":"—"}],"sdgs":["10","1"],"implementation":{"value":"funding","visibility":"public"},"scope":"local","areasOfActivity":[{"key":"06752","label":"Hessen (Kreis)"}],"activeInStates":[{"key":"06","label":"Hessen"}]},
    {"id":"a02","name":"Stiftung Lernwerk Spree","legalForm":"foundation","status":"active","fieldsOfAction":["languageAndLiteracy","democracyEducation","violencePrevention"],"primaryFieldOfAction":"languageAndLiteracy","educationStages":["upperSecondary","lowerSecondary"],"targetGroups":[{"role":"institutions","label":"—"},{"role":"funders","label":"—"}],"sdgs":["3"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"16","label":"Thüringen"}],"activeInStates":[{"key":"16","label":"Thüringen"}]},
    {"id":"a03","name":"Talentschmiede Lahn","legalForm":"UG","status":"active","fieldsOfAction":["democracyEducation"],"primaryFieldOfAction":"democracyEducation","educationStages":["adultEducation","lowerSecondary"],"targetGroups":[{"role":"multipliers","label":"—"}],"sdgs":["5"],"implementation":{"value":"both","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"08571","label":"Baden-Württemberg (Kreis)"}],"activeInStates":[{"key":"08","label":"Baden-Württemberg"}]},
    {"id":"a04","name":"Lernkompass Süd gGmbH","legalForm":"gGmbH","status":"active","fieldsOfAction":["civicEducation","careerOrientation","mentoring"],"primaryFieldOfAction":"civicEducation","educationStages":["vocational","adultEducation"],"targetGroups":[{"role":"beneficiaries","label":"—"}],"sdgs":["4","11"],"implementation":{"value":"operational","visibility":"public"},"scope":"national","areasOfActivity":[],"activeInStates":[]},
    {"id":"a05","name":"Zukunftswerkstatt Donau","legalForm":"eGbR","status":"active","fieldsOfAction":["careerOrientation","stemEducation"],"primaryFieldOfAction":"careerOrientation","educationStages":["primary","upperSecondary","lowerSecondary"],"targetGroups":[{"role":"funders","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["8","1"],"implementation":{"value":"funding","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"04","label":"Bremen"}],"activeInStates":[{"key":"04","label":"Bremen"}]},
    {"id":"a06","name":"Aufwind Ems","legalForm":"cooperative","status":"founding","fieldsOfAction":["violencePrevention","languageAndLiteracy"],"primaryFieldOfAction":"violencePrevention","educationStages":["primary","upperSecondary"],"targetGroups":[{"role":"multipliers","label":"—"}],"sdgs":["13"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"05836","label":"Nordrhein-Westfalen (Kreis)"}],"activeInStates":[{"key":"05","label":"Nordrhein-Westfalen"}]},
    {"id":"a07","name":"Lernlotsen Ruhr","legalForm":"publicLawCorporation","status":"active","fieldsOfAction":["sustainabilityEducation","interculturalEducation","stemEducation"],"primaryFieldOfAction":"sustainabilityEducation","educationStages":["upperSecondary","primary"],"targetGroups":[{"role":"funders","label":"—"},{"role":"policyMakers","label":"—"}],"sdgs":["16"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"08866","label":"Baden-Württemberg (Kreis)"},{"key":"01992","label":"Schleswig-Holstein (Kreis)"}],"activeInStates":[{"key":"01","label":"Schleswig-Holstein"},{"key":"08","label":"Baden-Württemberg"}]},
    {"id":"a08","name":"Lernzeit Ost e. V.","legalForm":"registeredAssociation","status":"active","fieldsOfAction":["democracyEducation","careerOrientation","violencePrevention"],"primaryFieldOfAction":"democracyEducation","educationStages":["upperSecondary"],"targetGroups":[{"role":"policyMakers","label":"—"},{"role":"funders","label":"—"}],"sdgs":["10","13"],"implementation":{"value":"both","visibility":"public"},"scope":"international","areasOfActivity":[],"activeInStates":[]},
    {"id":"a09","name":"Brückenschlag Donau gGmbH","legalForm":"gGmbH","status":"active","fieldsOfAction":["interculturalEducation"],"primaryFieldOfAction":"interculturalEducation","educationStages":["primary","adultEducation"],"targetGroups":[{"role":"beneficiaries","label":"—"}],"sdgs":["3","10"],"implementation":{"value":"both","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"05621","label":"Nordrhein-Westfalen (Kreis)"}],"activeInStates":[{"key":"05","label":"Nordrhein-Westfalen"}]},
    {"id":"a10","name":"Denkraum Rhein","legalForm":"informalGroup","status":"active","fieldsOfAction":["culturalEducation","inclusion","antiDiscrimination"],"primaryFieldOfAction":"culturalEducation","educationStages":["primary"],"targetGroups":[{"role":"beneficiaries","label":"—"}],"sdgs":["3","11"],"implementation":{"value":"both","visibility":"public"},"scope":"locationIndependent","areasOfActivity":[],"activeInStates":[]},
    {"id":"a11","name":"Stiftung Mitmachwerk Donau","legalForm":"foundation","status":"active","fieldsOfAction":["civicEducation"],"primaryFieldOfAction":"civicEducation","educationStages":["upperSecondary"],"targetGroups":[{"role":"beneficiaries","label":"—"}],"sdgs":["13"],"implementation":{"value":"operational","visibility":"public"},"scope":"local","areasOfActivity":[{"key":"09305","label":"Bayern (Kreis)"}],"activeInStates":[{"key":"09","label":"Bayern"}]},
    {"id":"a12","name":"Spurwechsel Süd gGmbH","legalForm":"gGmbH","status":"active","fieldsOfAction":["culturalEducation","democracyEducation"],"primaryFieldOfAction":"culturalEducation","educationStages":["upperSecondary"],"targetGroups":[{"role":"funders","label":"—"},{"role":"beneficiaries","label":"—"}],"sdgs":["3","10"],"implementation":{"value":"funding","visibility":"public"},"scope":"locationIndependent","areasOfActivity":[],"activeInStates":[]},
    {"id":"a13","name":"Bildungsanker Havel","legalForm":"UG","status":"active","fieldsOfAction":["democracyEducation","economicLiteracy"],"primaryFieldOfAction":"democracyEducation","educationStages":["upperSecondary"],"targetGroups":[{"role":"policyMakers","label":"—"}],"sdgs":["1","13"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"04703","label":"Bremen (Kreis)"},{"key":"11728","label":"Berlin (Kreis)"},{"key":"10116","label":"Saarland (Kreis)"}],"activeInStates":[{"key":"04","label":"Bremen"},{"key":"10","label":"Saarland"},{"key":"11","label":"Berlin"}]},
    {"id":"a14","name":"Stiftung Aufwind Lahn","legalForm":"foundation","status":"active","fieldsOfAction":["culturalEducation","volunteering"],"primaryFieldOfAction":"culturalEducation","educationStages":["earlyChildhood","adultEducation"],"targetGroups":[{"role":"funders","label":"—"}],"sdgs":["13","3"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"09558","label":"Bayern (Kreis)"},{"key":"08118","label":"Baden-Württemberg (Kreis)"},{"key":"14257","label":"Sachsen (Kreis)"}],"activeInStates":[{"key":"08","label":"Baden-Württemberg"},{"key":"09","label":"Bayern"},{"key":"14","label":"Sachsen"}]},
    {"id":"a15","name":"Wegmarke Nord e. V.","legalForm":"registeredAssociation","status":"active","fieldsOfAction":["stemEducation","antiDiscrimination"],"primaryFieldOfAction":"stemEducation","educationStages":["vocational","primary","adultEducation"],"targetGroups":[{"role":"policyMakers","label":"—"},{"role":"beneficiaries","label":"—"}],"sdgs":["10","8"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"01","label":"Schleswig-Holstein"},{"key":"08","label":"Baden-Württemberg"}],"activeInStates":[{"key":"01","label":"Schleswig-Holstein"},{"key":"08","label":"Baden-Württemberg"}]},
    {"id":"a16","name":"Wegmarke Main gGmbH","legalForm":"gGmbH","status":"active","fieldsOfAction":["mentoring","environmentalEducation"],"primaryFieldOfAction":"mentoring","educationStages":["upperSecondary"],"targetGroups":[{"role":"policyMakers","label":"—"}],"sdgs":["5"],"implementation":{"value":"both","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"10155","label":"Saarland (Kreis)"},{"key":"01469","label":"Schleswig-Holstein (Kreis)"}],"activeInStates":[{"key":"01","label":"Schleswig-Holstein"},{"key":"10","label":"Saarland"}]},
    {"id":"a17","name":"Brückenschlag Main","legalForm":"eGbR","status":"dormant","fieldsOfAction":["healthEducation","interculturalEducation"],"primaryFieldOfAction":"healthEducation","educationStages":["lowerSecondary","adultEducation"],"targetGroups":[{"role":"beneficiaries","label":"—"}],"sdgs":["5"],"implementation":{"value":"both","visibility":"public"},"scope":"national","areasOfActivity":[],"activeInStates":[]},
    {"id":"a18","name":"Talentschmiede Spree e. V.","legalForm":"registeredAssociation","status":"active","fieldsOfAction":["inclusion","languageAndLiteracy"],"primaryFieldOfAction":"inclusion","educationStages":["earlyChildhood"],"targetGroups":[{"role":"multipliers","label":"—"},{"role":"policyMakers","label":"—"}],"sdgs":["10"],"implementation":{"value":"funding","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"04","label":"Bremen"}],"activeInStates":[{"key":"04","label":"Bremen"}]},
    {"id":"a19","name":"Stiftung Perspektivwerk Lahn","legalForm":"foundation","status":"active","fieldsOfAction":["familyEducation","mentoring","volunteering"],"primaryFieldOfAction":"familyEducation","educationStages":["upperSecondary","lowerSecondary","adultEducation"],"targetGroups":[{"role":"beneficiaries","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["4"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"11948","label":"Berlin (Kreis)"},{"key":"16723","label":"Thüringen (Kreis)"},{"key":"04487","label":"Bremen (Kreis)"}],"activeInStates":[{"key":"04","label":"Bremen"},{"key":"11","label":"Berlin"},{"key":"16","label":"Thüringen"}]},
    {"id":"a20","name":"Bildungsbrücke Ruhr gGmbH","legalForm":"gGmbH","status":"active","fieldsOfAction":["sustainabilityEducation"],"primaryFieldOfAction":"sustainabilityEducation","educationStages":["lowerSecondary"],"targetGroups":[{"role":"policyMakers","label":"—"}],"sdgs":["5","1"],"implementation":{"value":"both","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"13","label":"Mecklenburg-Vorpommern"},{"key":"07","label":"Rheinland-Pfalz"}],"activeInStates":[{"key":"07","label":"Rheinland-Pfalz"},{"key":"13","label":"Mecklenburg-Vorpommern"}]},
    {"id":"a21","name":"Stiftung Zukunftswerkstatt Main","legalForm":"foundation","status":"active","fieldsOfAction":["sustainabilityEducation","democracyEducation","mentoring"],"primaryFieldOfAction":"sustainabilityEducation","educationStages":["lowerSecondary","upperSecondary"],"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["11"],"implementation":{"value":"both","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"06384","label":"Hessen (Kreis)"}],"activeInStates":[{"key":"06","label":"Hessen"}]},
    {"id":"a22","name":"Stiftung Bildungsbrücke West","legalForm":"foundation","status":"active","fieldsOfAction":["digitalEducation","careerOrientation","healthEducation"],"primaryFieldOfAction":"digitalEducation","educationStages":["upperSecondary"],"targetGroups":[{"role":"multipliers","label":"—"}],"sdgs":["10"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"14","label":"Sachsen"}],"activeInStates":[{"key":"14","label":"Sachsen"}]},
    {"id":"a23","name":"Impulswerk Saar e. V.","legalForm":"registeredAssociation","status":"active","fieldsOfAction":["mentoring","stemEducation","digitalEducation"],"primaryFieldOfAction":"mentoring","educationStages":["upperSecondary"],"targetGroups":[{"role":"multipliers","label":"—"},{"role":"funders","label":"—"}],"sdgs":["1","11"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"01135","label":"Schleswig-Holstein (Kreis)"},{"key":"06961","label":"Hessen (Kreis)"},{"key":"08591","label":"Baden-Württemberg (Kreis)"}],"activeInStates":[{"key":"01","label":"Schleswig-Holstein"},{"key":"06","label":"Hessen"},{"key":"08","label":"Baden-Württemberg"}]},
    {"id":"a24","name":"Bildungsbrücke Weser e. V.","legalForm":"registeredAssociation","status":"active","fieldsOfAction":["economicLiteracy"],"primaryFieldOfAction":"economicLiteracy","educationStages":["adultEducation","upperSecondary","vocational"],"targetGroups":[{"role":"funders","label":"—"}],"sdgs":["5","4"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"12","label":"Brandenburg"},{"key":"09","label":"Bayern"}],"activeInStates":[{"key":"09","label":"Bayern"},{"key":"12","label":"Brandenburg"}]},
    {"id":"a25","name":"Bildungsanker Main e. V.","legalForm":"registeredAssociation","status":"active","fieldsOfAction":["interculturalEducation","volunteering","culturalEducation"],"primaryFieldOfAction":"interculturalEducation","educationStages":["primary","adultEducation"],"targetGroups":[{"role":"multipliers","label":"—"}],"sdgs":["1","4"],"implementation":{"value":"operational","visibility":"public"},"scope":"national","areasOfActivity":[],"activeInStates":[]},
    {"id":"a26","name":"Perspektivwerk West","legalForm":"cooperative","status":"active","fieldsOfAction":["healthEducation"],"primaryFieldOfAction":"healthEducation","educationStages":["adultEducation"],"targetGroups":[{"role":"policyMakers","label":"—"}],"sdgs":["10"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"11744","label":"Berlin (Kreis)"}],"activeInStates":[{"key":"11","label":"Berlin"}]},
    {"id":"a27","name":"Bildungsanker Ost","legalForm":"cooperative","status":"active","fieldsOfAction":["stemEducation","languageAndLiteracy"],"primaryFieldOfAction":"stemEducation","educationStages":["lowerSecondary","vocational","primary"],"targetGroups":[{"role":"policyMakers","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["10","13"],"implementation":{"value":"funding","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"04101","label":"Bremen (Kreis)"},{"key":"05818","label":"Nordrhein-Westfalen (Kreis)"},{"key":"16796","label":"Thüringen (Kreis)"}],"activeInStates":[{"key":"04","label":"Bremen"},{"key":"05","label":"Nordrhein-Westfalen"},{"key":"16","label":"Thüringen"}]},
    {"id":"a28","name":"Bildungspfad Ems","legalForm":"eGbR","status":"active","fieldsOfAction":["civicEducation","interculturalEducation"],"primaryFieldOfAction":"civicEducation","educationStages":["upperSecondary"],"targetGroups":[{"role":"policyMakers","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["13"],"implementation":{"value":"both","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"13","label":"Mecklenburg-Vorpommern"},{"key":"15","label":"Sachsen-Anhalt"}],"activeInStates":[{"key":"13","label":"Mecklenburg-Vorpommern"},{"key":"15","label":"Sachsen-Anhalt"}]},
    {"id":"a29","name":"Lernkompass West","legalForm":"eGbR","status":"active","fieldsOfAction":["mentoring"],"primaryFieldOfAction":"mentoring","educationStages":["upperSecondary"],"targetGroups":[{"role":"beneficiaries","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["13","8"],"implementation":{"value":"both","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"02","label":"Hamburg"}],"activeInStates":[{"key":"02","label":"Hamburg"}]},
    {"id":"a30","name":"Stiftung Lernkompass Main","legalForm":"foundation","status":"active","fieldsOfAction":["careerOrientation"],"primaryFieldOfAction":"careerOrientation","educationStages":["lowerSecondary","upperSecondary","vocational"],"targetGroups":[{"role":"policyMakers","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["3","5"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"14","label":"Sachsen"},{"key":"16","label":"Thüringen"}],"activeInStates":[{"key":"14","label":"Sachsen"},{"key":"16","label":"Thüringen"}]},
    {"id":"a31","name":"Talentschmiede Ems","legalForm":"eGbR","status":"active","fieldsOfAction":["languageAndLiteracy"],"primaryFieldOfAction":"languageAndLiteracy","educationStages":["primary","earlyChildhood","lowerSecondary"],"targetGroups":[{"role":"funders","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["16"],"implementation":{"value":"operational","visibility":"public"},"scope":"locationIndependent","areasOfActivity":[],"activeInStates":[]},
    {"id":"a32","name":"Lernwerk Rhein","legalForm":"UG","status":"active","fieldsOfAction":["healthEducation","volunteering"],"primaryFieldOfAction":"healthEducation","educationStages":["lowerSecondary","primary"],"targetGroups":[{"role":"funders","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["16","5"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"11","label":"Berlin"},{"key":"15","label":"Sachsen-Anhalt"}],"activeInStates":[{"key":"11","label":"Berlin"},{"key":"15","label":"Sachsen-Anhalt"}]},
    {"id":"a33","name":"Perspektivwerk Donau","legalForm":"UG","status":"active","fieldsOfAction":["economicLiteracy","careerOrientation","civicEducation"],"primaryFieldOfAction":"economicLiteracy","educationStages":["vocational","lowerSecondary"],"targetGroups":[{"role":"policyMakers","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["3","10"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"09739","label":"Bayern (Kreis)"}],"activeInStates":[{"key":"09","label":"Bayern"}]},
    {"id":"a34","name":"Perspektivwerk Saar","legalForm":"informalGroup","status":"active","fieldsOfAction":["languageAndLiteracy"],"primaryFieldOfAction":"languageAndLiteracy","educationStages":["earlyChildhood","lowerSecondary"],"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["11","4"],"implementation":{"value":"operational","visibility":"public"},"scope":"international","areasOfActivity":[],"activeInStates":[]},
    {"id":"a35","name":"Talentschmiede Rhein gGmbH","legalForm":"gGmbH","status":"active","fieldsOfAction":["inclusion","digitalEducation"],"primaryFieldOfAction":"inclusion","educationStages":["primary","adultEducation"],"targetGroups":[{"role":"policyMakers","label":"—"}],"sdgs":["1","4"],"implementation":{"value":"both","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"09795","label":"Bayern (Kreis)"},{"key":"16577","label":"Thüringen (Kreis)"}],"activeInStates":[{"key":"09","label":"Bayern"},{"key":"16","label":"Thüringen"}]},
    {"id":"a36","name":"Mitmachwerk Main","legalForm":"cooperative","status":"active","fieldsOfAction":["languageAndLiteracy","interculturalEducation"],"primaryFieldOfAction":"languageAndLiteracy","educationStages":["primary"],"targetGroups":[{"role":"beneficiaries","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["1","11"],"implementation":{"value":"operational","visibility":"public"},"scope":"local","areasOfActivity":[{"key":"02108","label":"Hamburg (Kreis)"},{"key":"11420","label":"Berlin (Kreis)"},{"key":"14223","label":"Sachsen (Kreis)"}],"activeInStates":[{"key":"02","label":"Hamburg"},{"key":"11","label":"Berlin"},{"key":"14","label":"Sachsen"}]}
  ];

  global.EduStandard = global.EduStandard || {};
  global.EduStandard.akteure = AKTEURE;
})(window);
