/*
 * Fiktiver Akteursbestand — v0-Arbeitsstand.
 *
 * 36 erfundene Organisationen, schemakonform nach fields.js.
 * Grundlage fuer die Netzdarstellung (schema.html) und die Kreuztabelle
 * (simulation.html). Kein Bezug zu realen Organisationen: Namen sind aus
 * festen Bausteinen zusammengesetzt, Kennzahlen deterministisch erzeugt.
 *
 * Die Eintraege tragen bewusst keine Wikidata-Kennung und keine Adressen —
 * eine QID verweist stets auf eine reale Organisation.
 */

(function (global) {
  'use strict';

  var AKTEURE = [
    {"id":"a01","name":"Denkraum Elbe e. V.","legalForm":"registeredAssociation","status":"aktiv","fieldsOfAction":["sprachbildung"],"primaryFieldOfAction":"sprachbildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["primarstufe"],"quelle":"abgeleitet"},"targetGroups":[{"role":"multipliers","label":"—"}],"sdgs":["10","1"],"implementation":{"value":"funding","visibility":"public"},"scope":"local","areasOfActivity":[{"key":"06752","label":"Hessen (Kreis)"}],"activeInStates":[{"key":"06","label":"Hessen"}]},
    {"id":"a02","name":"Stiftung Lernwerk Spree","legalForm":"foundation","status":"aktiv","fieldsOfAction":["sprachbildung","politische_bildung","gesundheit_praevention"],"primaryFieldOfAction":"sprachbildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2","sekundarstufe_1"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["3"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"16","label":"Thüringen"}],"activeInStates":[{"key":"16","label":"Thüringen"}]},
    {"id":"a03","name":"Talentschmiede Lahn","legalForm":"UG","status":"aktiv","fieldsOfAction":["politische_bildung"],"primaryFieldOfAction":"politische_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["quartaerbereich","sekundarstufe_1"],"quelle":"abgeleitet"},"targetGroups":[{"role":"multipliers","label":"—"}],"sdgs":["5"],"implementation":{"value":"both","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"08571","label":"Baden-Württemberg (Kreis)"}],"activeInStates":[{"key":"08","label":"Baden-Württemberg"}]},
    {"id":"a04","name":"Lernkompass Süd gGmbH","legalForm":"gGmbH","status":"aktiv","fieldsOfAction":["politische_bildung","persoenlichkeitsentwicklung"],"primaryFieldOfAction":"politische_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2","quartaerbereich"],"quelle":"abgeleitet"},"targetGroups":[{"role":"beneficiaries","label":"—"}],"sdgs":["4","11"],"implementation":{"value":"operational","visibility":"public"},"scope":"national","areasOfActivity":[],"activeInStates":[]},
    {"id":"a05","name":"Zukunftswerkstatt Donau","legalForm":"eGbR","status":"aktiv","fieldsOfAction":["mint_bildung"],"primaryFieldOfAction":"mint_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["primarstufe","sekundarstufe_2","sekundarstufe_1"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["8","1"],"implementation":{"value":"funding","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"04","label":"Bremen"}],"activeInStates":[{"key":"04","label":"Bremen"}]},
    {"id":"a06","name":"Aufwind Ems","legalForm":"cooperative","status":"aktiv","fieldsOfAction":["gesundheit_praevention","sprachbildung"],"primaryFieldOfAction":"gesundheit_praevention","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["primarstufe","sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"multipliers","label":"—"}],"sdgs":["13"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"05836","label":"Nordrhein-Westfalen (Kreis)"}],"activeInStates":[{"key":"05","label":"Nordrhein-Westfalen"}]},
    {"id":"a07","name":"Lernlotsen Ruhr","legalForm":"publicLawCorporation","status":"aktiv","fieldsOfAction":["bne","interkulturelle_bildung","mint_bildung"],"primaryFieldOfAction":"bne","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2","primarstufe"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["16"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"08866","label":"Baden-Württemberg (Kreis)"},{"key":"01992","label":"Schleswig-Holstein (Kreis)"}],"activeInStates":[{"key":"01","label":"Schleswig-Holstein"},{"key":"08","label":"Baden-Württemberg"}]},
    {"id":"a08","name":"Lernzeit Ost e. V.","legalForm":"registeredAssociation","status":"aktiv","fieldsOfAction":["politische_bildung","gesundheit_praevention"],"primaryFieldOfAction":"politische_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["10","13"],"implementation":{"value":"both","visibility":"public"},"scope":"international","areasOfActivity":[],"activeInStates":[]},
    {"id":"a09","name":"Brückenschlag Donau gGmbH","legalForm":"gGmbH","status":"aktiv","fieldsOfAction":["interkulturelle_bildung"],"primaryFieldOfAction":"interkulturelle_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["primarstufe","quartaerbereich"],"quelle":"abgeleitet"},"targetGroups":[{"role":"beneficiaries","label":"—"}],"sdgs":["3","10"],"implementation":{"value":"both","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"05621","label":"Nordrhein-Westfalen (Kreis)"}],"activeInStates":[{"key":"05","label":"Nordrhein-Westfalen"}]},
    {"id":"a10","name":"Denkraum Rhein","legalForm":"informalGroup","status":"aktiv","fieldsOfAction":["kulturelle_bildung","inklusion","diversitaet"],"primaryFieldOfAction":"kulturelle_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["primarstufe"],"quelle":"abgeleitet"},"targetGroups":[{"role":"beneficiaries","label":"—"}],"sdgs":["3","11"],"implementation":{"value":"both","visibility":"public"},"scope":"locationIndependent","areasOfActivity":[],"activeInStates":[]},
    {"id":"a11","name":"Stiftung Mitmachwerk Donau","legalForm":"foundation","status":"aktiv","fieldsOfAction":["politische_bildung"],"primaryFieldOfAction":"politische_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"beneficiaries","label":"—"}],"sdgs":["13"],"implementation":{"value":"operational","visibility":"public"},"scope":"local","areasOfActivity":[{"key":"09305","label":"Bayern (Kreis)"}],"activeInStates":[{"key":"09","label":"Bayern"}]},
    {"id":"a12","name":"Spurwechsel Süd gGmbH","legalForm":"gGmbH","status":"aktiv","fieldsOfAction":["kulturelle_bildung","politische_bildung"],"primaryFieldOfAction":"kulturelle_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"beneficiaries","label":"—"}],"sdgs":["3","10"],"implementation":{"value":"funding","visibility":"public"},"scope":"locationIndependent","areasOfActivity":[],"activeInStates":[]},
    {"id":"a13","name":"Bildungsanker Havel","legalForm":"UG","status":"aktiv","fieldsOfAction":["politische_bildung","wirtschaft"],"primaryFieldOfAction":"politische_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["1","13"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"04703","label":"Bremen (Kreis)"},{"key":"11728","label":"Berlin (Kreis)"},{"key":"10116","label":"Saarland (Kreis)"}],"activeInStates":[{"key":"04","label":"Bremen"},{"key":"10","label":"Saarland"},{"key":"11","label":"Berlin"}]},
    {"id":"a14","name":"Stiftung Aufwind Lahn","legalForm":"foundation","status":"aktiv","fieldsOfAction":["kulturelle_bildung","engagementfoerderung"],"primaryFieldOfAction":"kulturelle_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["elementarbereich","quartaerbereich"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["13","3"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"09558","label":"Bayern (Kreis)"},{"key":"08118","label":"Baden-Württemberg (Kreis)"},{"key":"14257","label":"Sachsen (Kreis)"}],"activeInStates":[{"key":"08","label":"Baden-Württemberg"},{"key":"09","label":"Bayern"},{"key":"14","label":"Sachsen"}]},
    {"id":"a15","name":"Wegmarke Nord e. V.","legalForm":"registeredAssociation","status":"aktiv","fieldsOfAction":["mint_bildung","diversitaet"],"primaryFieldOfAction":"mint_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2","primarstufe","quartaerbereich"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"beneficiaries","label":"—"}],"sdgs":["10","8"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"01","label":"Schleswig-Holstein"},{"key":"08","label":"Baden-Württemberg"}],"activeInStates":[{"key":"01","label":"Schleswig-Holstein"},{"key":"08","label":"Baden-Württemberg"}]},
    {"id":"a16","name":"Wegmarke Main gGmbH","legalForm":"gGmbH","status":"aktiv","fieldsOfAction":["persoenlichkeitsentwicklung","bne"],"primaryFieldOfAction":"persoenlichkeitsentwicklung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["5"],"implementation":{"value":"both","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"10155","label":"Saarland (Kreis)"},{"key":"01469","label":"Schleswig-Holstein (Kreis)"}],"activeInStates":[{"key":"01","label":"Schleswig-Holstein"},{"key":"10","label":"Saarland"}]},
    {"id":"a17","name":"Brückenschlag Main","legalForm":"eGbR","status":"ruhend","fieldsOfAction":["gesundheit_praevention","interkulturelle_bildung"],"primaryFieldOfAction":"gesundheit_praevention","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_1","quartaerbereich"],"quelle":"abgeleitet"},"targetGroups":[{"role":"beneficiaries","label":"—"}],"sdgs":["5"],"implementation":{"value":"both","visibility":"public"},"scope":"national","areasOfActivity":[],"activeInStates":[]},
    {"id":"a18","name":"Talentschmiede Spree e. V.","legalForm":"registeredAssociation","status":"aktiv","fieldsOfAction":["inklusion","sprachbildung"],"primaryFieldOfAction":"inklusion","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["elementarbereich"],"quelle":"abgeleitet"},"targetGroups":[{"role":"multipliers","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["10"],"implementation":{"value":"funding","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"04","label":"Bremen"}],"activeInStates":[{"key":"04","label":"Bremen"}]},
    {"id":"a19","name":"Stiftung Perspektivwerk Lahn","legalForm":"foundation","status":"aktiv","fieldsOfAction":["familienbildung","persoenlichkeitsentwicklung","engagementfoerderung"],"primaryFieldOfAction":"familienbildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2","sekundarstufe_1","quartaerbereich"],"quelle":"abgeleitet"},"targetGroups":[{"role":"beneficiaries","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["4"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"11948","label":"Berlin (Kreis)"},{"key":"16723","label":"Thüringen (Kreis)"},{"key":"04487","label":"Bremen (Kreis)"}],"activeInStates":[{"key":"04","label":"Bremen"},{"key":"11","label":"Berlin"},{"key":"16","label":"Thüringen"}]},
    {"id":"a20","name":"Bildungsbrücke Ruhr gGmbH","legalForm":"gGmbH","status":"aktiv","fieldsOfAction":["bne"],"primaryFieldOfAction":"bne","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_1"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["5","1"],"implementation":{"value":"both","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"13","label":"Mecklenburg-Vorpommern"},{"key":"07","label":"Rheinland-Pfalz"}],"activeInStates":[{"key":"07","label":"Rheinland-Pfalz"},{"key":"13","label":"Mecklenburg-Vorpommern"}]},
    {"id":"a21","name":"Stiftung Zukunftswerkstatt Main","legalForm":"foundation","status":"aktiv","fieldsOfAction":["bne","politische_bildung","persoenlichkeitsentwicklung"],"primaryFieldOfAction":"bne","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_1","sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["11"],"implementation":{"value":"both","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"06384","label":"Hessen (Kreis)"}],"activeInStates":[{"key":"06","label":"Hessen"}]},
    {"id":"a22","name":"Stiftung Bildungsbrücke West","legalForm":"foundation","status":"aktiv","fieldsOfAction":["digitale_transformation","gesundheit_praevention"],"primaryFieldOfAction":"digitale_transformation","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"multipliers","label":"—"}],"sdgs":["10"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"14","label":"Sachsen"}],"activeInStates":[{"key":"14","label":"Sachsen"}]},
    {"id":"a23","name":"Impulswerk Saar e. V.","legalForm":"registeredAssociation","status":"aktiv","fieldsOfAction":["persoenlichkeitsentwicklung","mint_bildung","digitale_transformation"],"primaryFieldOfAction":"persoenlichkeitsentwicklung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"multipliers","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["1","11"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"01135","label":"Schleswig-Holstein (Kreis)"},{"key":"06961","label":"Hessen (Kreis)"},{"key":"08591","label":"Baden-Württemberg (Kreis)"}],"activeInStates":[{"key":"01","label":"Schleswig-Holstein"},{"key":"06","label":"Hessen"},{"key":"08","label":"Baden-Württemberg"}]},
    {"id":"a24","name":"Bildungsbrücke Weser e. V.","legalForm":"registeredAssociation","status":"aktiv","fieldsOfAction":["wirtschaft"],"primaryFieldOfAction":"wirtschaft","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["quartaerbereich","sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["5","4"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"12","label":"Brandenburg"},{"key":"09","label":"Bayern"}],"activeInStates":[{"key":"09","label":"Bayern"},{"key":"12","label":"Brandenburg"}]},
    {"id":"a25","name":"Bildungsanker Main e. V.","legalForm":"registeredAssociation","status":"aktiv","fieldsOfAction":["interkulturelle_bildung","engagementfoerderung","kulturelle_bildung"],"primaryFieldOfAction":"interkulturelle_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["primarstufe","quartaerbereich"],"quelle":"abgeleitet"},"targetGroups":[{"role":"multipliers","label":"—"}],"sdgs":["1","4"],"implementation":{"value":"operational","visibility":"public"},"scope":"national","areasOfActivity":[],"activeInStates":[]},
    {"id":"a26","name":"Perspektivwerk West","legalForm":"cooperative","status":"aktiv","fieldsOfAction":["gesundheit_praevention"],"primaryFieldOfAction":"gesundheit_praevention","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["quartaerbereich"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["10"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"11744","label":"Berlin (Kreis)"}],"activeInStates":[{"key":"11","label":"Berlin"}]},
    {"id":"a27","name":"Bildungsanker Ost","legalForm":"cooperative","status":"aktiv","fieldsOfAction":["mint_bildung","sprachbildung"],"primaryFieldOfAction":"mint_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_1","sekundarstufe_2","primarstufe"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["10","13"],"implementation":{"value":"funding","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"04101","label":"Bremen (Kreis)"},{"key":"05818","label":"Nordrhein-Westfalen (Kreis)"},{"key":"16796","label":"Thüringen (Kreis)"}],"activeInStates":[{"key":"04","label":"Bremen"},{"key":"05","label":"Nordrhein-Westfalen"},{"key":"16","label":"Thüringen"}]},
    {"id":"a28","name":"Bildungspfad Ems","legalForm":"eGbR","status":"aktiv","fieldsOfAction":["politische_bildung","interkulturelle_bildung"],"primaryFieldOfAction":"politische_bildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"institutions","label":"—"}],"sdgs":["13"],"implementation":{"value":"both","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"13","label":"Mecklenburg-Vorpommern"},{"key":"15","label":"Sachsen-Anhalt"}],"activeInStates":[{"key":"13","label":"Mecklenburg-Vorpommern"},{"key":"15","label":"Sachsen-Anhalt"}]},
    {"id":"a29","name":"Lernkompass West","legalForm":"eGbR","status":"aktiv","fieldsOfAction":["persoenlichkeitsentwicklung"],"primaryFieldOfAction":"persoenlichkeitsentwicklung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"beneficiaries","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["13","8"],"implementation":{"value":"both","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"02","label":"Hamburg"}],"activeInStates":[{"key":"02","label":"Hamburg"}]},
    {"id":"a30","name":"Stiftung Lernkompass Main","legalForm":"foundation","status":"aktiv","fieldsOfAction":["wirtschaft"],"primaryFieldOfAction":"wirtschaft","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_1","sekundarstufe_2"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["3","5"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"14","label":"Sachsen"},{"key":"16","label":"Thüringen"}],"activeInStates":[{"key":"14","label":"Sachsen"},{"key":"16","label":"Thüringen"}]},
    {"id":"a31","name":"Talentschmiede Ems","legalForm":"eGbR","status":"aktiv","fieldsOfAction":["sprachbildung"],"primaryFieldOfAction":"sprachbildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["primarstufe","elementarbereich","sekundarstufe_1"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["16"],"implementation":{"value":"operational","visibility":"public"},"scope":"locationIndependent","areasOfActivity":[],"activeInStates":[]},
    {"id":"a32","name":"Lernwerk Rhein","legalForm":"UG","status":"aktiv","fieldsOfAction":["gesundheit_praevention","engagementfoerderung"],"primaryFieldOfAction":"gesundheit_praevention","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_1","primarstufe"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["16","5"],"implementation":{"value":"operational","visibility":"public"},"scope":"state","areasOfActivity":[{"key":"11","label":"Berlin"},{"key":"15","label":"Sachsen-Anhalt"}],"activeInStates":[{"key":"11","label":"Berlin"},{"key":"15","label":"Sachsen-Anhalt"}]},
    {"id":"a33","name":"Perspektivwerk Donau","legalForm":"UG","status":"aktiv","fieldsOfAction":["wirtschaft","politische_bildung"],"primaryFieldOfAction":"wirtschaft","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["sekundarstufe_2","sekundarstufe_1"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["3","10"],"implementation":{"value":"operational","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"09739","label":"Bayern (Kreis)"}],"activeInStates":[{"key":"09","label":"Bayern"}]},
    {"id":"a34","name":"Perspektivwerk Saar","legalForm":"informalGroup","status":"aktiv","fieldsOfAction":["sprachbildung"],"primaryFieldOfAction":"sprachbildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["elementarbereich","sekundarstufe_1"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["11","4"],"implementation":{"value":"operational","visibility":"public"},"scope":"international","areasOfActivity":[],"activeInStates":[]},
    {"id":"a35","name":"Talentschmiede Rhein gGmbH","legalForm":"gGmbH","status":"aktiv","fieldsOfAction":["inklusion","digitale_transformation"],"primaryFieldOfAction":"inklusion","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["primarstufe","quartaerbereich"],"quelle":"abgeleitet"},"targetGroups":[{"role":"institutions","label":"—"}],"sdgs":["1","4"],"implementation":{"value":"both","visibility":"public"},"scope":"regional","areasOfActivity":[{"key":"09795","label":"Bayern (Kreis)"},{"key":"16577","label":"Thüringen (Kreis)"}],"activeInStates":[{"key":"09","label":"Bayern"},{"key":"16","label":"Thüringen"}]},
    {"id":"a36","name":"Mitmachwerk Main","legalForm":"cooperative","status":"aktiv","fieldsOfAction":["sprachbildung","interkulturelle_bildung"],"primaryFieldOfAction":"sprachbildung","educationStages":{"modell":"bildungsstruktur-bereiche","werte":["primarstufe"],"quelle":"abgeleitet"},"targetGroups":[{"role":"beneficiaries","label":"—"},{"role":"multipliers","label":"—"}],"sdgs":["1","11"],"implementation":{"value":"operational","visibility":"public"},"scope":"local","areasOfActivity":[{"key":"02108","label":"Hamburg (Kreis)"},{"key":"11420","label":"Berlin (Kreis)"},{"key":"14223","label":"Sachsen (Kreis)"}],"activeInStates":[{"key":"02","label":"Hamburg"},{"key":"11","label":"Berlin"},{"key":"14","label":"Sachsen"}]}
  ];

  global.EduStandard = global.EduStandard || {};
  global.EduStandard.akteure = AKTEURE;
})(window);
